apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-my-prod-grading
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grading
        workload.user.cattle.io/workloadselector: apps.deployment-my-prod-grading
      namespace: my-prod
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: common-secret
                optional: false
            - secretRef:
                name: grading-secret
                optional: false
          image: harbor.pg.innopolis.university/my-mini/backend/api/grading:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 8
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          name: grading
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 8
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: pg-harbor
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
