// <auto-generated />
using System;
using System.Collections.Generic;
using BuildingBlocks.Domain;
using GradingModule.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradingModule.Infrastructure.Migrations
{
    [DbContext(typeof(GradingContext))]
    [Migration("20251203145610_SubmissionRelationships")]
    partial class SubmissionRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradingModule.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LangStr>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid[]>("FileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsGroupAssignment")
                        .HasColumnType("boolean");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.AssignmentComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<LangStr>("Description")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid[]>("FileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentComponent", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.ComponentGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourseParticipantId")
                        .HasColumnType("uuid");

                    b.Property<LangStr>("Feedback")
                        .HasColumnType("jsonb");

                    b.Property<List<Guid>>("FileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("CourseParticipantId");

                    b.HasIndex("GroupId");

                    b.ToTable("ComponentGrade", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CourseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.CourseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CourseParticipant", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<LangStr>("Description")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<LangStr>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.PeerReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AssignedGrade")
                        .HasColumnType("integer");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourseParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("CourseParticipantId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("PeerReview", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("FileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedByGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmittedByParticipantId")
                        .HasColumnType("uuid");

                    b.Property<LangStr>("Text")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("SubmittedByGroupId");

                    b.HasIndex("SubmittedByParticipantId");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.AssignmentComponent", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Components")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.ComponentGrade", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.AssignmentComponent", "Component")
                        .WithMany("Grades")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingModule.Domain.Entities.CourseParticipant", "CourseParticipant")
                        .WithMany("Grades")
                        .HasForeignKey("CourseParticipantId");

                    b.HasOne("GradingModule.Domain.Entities.Group", "Group")
                        .WithMany("Grades")
                        .HasForeignKey("GroupId");

                    b.Navigation("Component");

                    b.Navigation("CourseParticipant");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.CourseParticipant", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.Course", "Course")
                        .WithMany("CourseParticipants")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingModule.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId");

                    b.HasOne("GradingModule.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("GradingModule.Domain.Entities.CourseParticipant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Group", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.PeerReview", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.AssignmentComponent", "Component")
                        .WithMany("PeerReviews")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingModule.Domain.Entities.CourseParticipant", "CourseParticipant")
                        .WithMany()
                        .HasForeignKey("CourseParticipantId");

                    b.HasOne("GradingModule.Domain.Entities.Group", "Group")
                        .WithMany("AuthoredPeerReviews")
                        .HasForeignKey("GroupId");

                    b.HasOne("GradingModule.Domain.Entities.Submission", "Submission")
                        .WithMany("ReceivedPeerReviews")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("CourseParticipant");

                    b.Navigation("Group");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Submission", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.AssignmentComponent", "Component")
                        .WithMany("Submissions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingModule.Domain.Entities.Group", "SubmittedByGroup")
                        .WithMany("Submissions")
                        .HasForeignKey("SubmittedByGroupId");

                    b.HasOne("GradingModule.Domain.Entities.CourseParticipant", "SubmittedByParticipant")
                        .WithMany("Submissions")
                        .HasForeignKey("SubmittedByParticipantId");

                    b.Navigation("Component");

                    b.Navigation("SubmittedByGroup");

                    b.Navigation("SubmittedByParticipant");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("GradingModule.Domain.Entities.Course", "Course")
                        .WithMany("Teachers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingModule.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("GradingModule.Domain.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.AssignmentComponent", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("PeerReviews");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CourseParticipants");

                    b.Navigation("Groups");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.CourseParticipant", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Group", b =>
                {
                    b.Navigation("AuthoredPeerReviews");

                    b.Navigation("Grades");

                    b.Navigation("Members");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GradingModule.Domain.Entities.Submission", b =>
                {
                    b.Navigation("ReceivedPeerReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
